[package]
name = "to"
version = "0.1.0"
authors = ["Nelson Earle <nelson.earle137@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
structopt = "0.3.14"
syn = "1.0.31"
quote = "1.0.7"
